from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
import chromadb 
import os 
from sentence_transformers import SentenceTransformer


